export const statesData = [
    {
        id: 1,
        state: "Abia State",
        localGovernmentAreas: [
            "Aba North",
            "Aba South",
            "Isiala Ngwa North",
            "Isiala Ngwa South",
            "Obingwa",
            "Osisioma Ngwa",
            "Ugwunagbo",
            "Ukwa East",
            "Ukwa West",
            "Umuahia North",
            "Umuahia South",
            "Ikwuano",
            "Bende",
            "Ohafia",
            "Arochukwu",
            "Item"
        ]
    },
    {
        id: 2,
        state: "Adamawa State",
        localGovernmentAreas: [
            "Demsa",
            "Fufore",
            "Ganye",
            "Girei",
            "Gombi",
            "Grie",
            "Hong",
            "Jada",
            "Lamurde",
            "Mubi North",
            "Mubi South",
            "Numan",
            "Shelleng",
            "Song",
            "Toungo",
            "Yola North",
            "Yola South"
        ]
    },
    {
        id: 3,
        state: "Akwa Ibom State",
        localGovernmentAreas: [
            "Abak",
            "Eastern Obolo",
            "Eket",
            "Esit Eket",
            "Etim Ekpo",
            "Etinan",
            "Ibiono Ibom",
            "Ibesikpo Asutan",
            "Ikono",
            "Ikot Abasi",
            "Ikot Ekpene",
            "Ini",
            "Itu",
            "Mbo",
            "Mkpat Enin",
            "Nsit Atai",
            "Nsit Ibom",
            "Obot Akara",
            "Okobo",
            "Oron",
            "Oruk Anam",
            "Uruan",
            "Urue Offong Oruko",
            "Ikot Ekpene",
            "Uyo"
        ]
    },
    {
        id: 4,
        state: "Anambra State",
        localGovernmentAreas: [
            "Aguata",
            "Anambra East",
            "Anambra West",
            "Awka North",
            "Awka South",
            "Dunukofia",
            "Ekwusigo",
            "Idemili North",
            "Idemili South",
            "Ihiala",
            "Njikoka",
            "Nnewi North",
            "Nnewi South",
            "Ogbaru",
            "Onitsha North",
            "Onitsha South",
            "Orumba North",
            "Orumba South",
            "Oyi"
        ]
    },
    {
        id: 5,
        state: "Bauchi State",
        localGovernmentAreas: [
            "Alkaleri",
            "Bauchi",
            "Bogoro",
            "Darazo",
            "Dass",
            "Misau",
            "Ningi",
            "Shira",
            "Tafawa Balewa",
            "Toro",
            "Warji",
            "Zaki"
        ]
    },
    {
        id: 6,
        state: "Bayelsa State",
        localGovernmentAreas: [
            "Brass",
            "Ekere",
            "Nembe",
            "Ogbia",
            "Sagbama",
            "Southern Ijaw",
            "Yenagoa"
        ]
    },
    {
        id: 7,
        state: "Benue State",
        localGovernmentAreas: [
            "Ado",
            "Agatu",
            "Apa",
            "Buruku",
            "Gboko",
            "Guma",
            "Gwer East",
            "Gwer West",
            "Katsina-Ala",
            "Konshisha",
            "Otukpo",
            "Ogbadibo",
            "Ohimini",
            "Okpokwu",
            "Oturkpo",
            "Tarka",
            "Vandeikya"
        ]
    },
    {
        id: 8,
        state: "Borno State",
        localGovernmentAreas: [
            "Abadam",
            "Askira/Uba",
            "Bama",
            "Bayo",
            "Chibok",
            "Damboa",
            "Dikwa",
            "Gubio",
            "Guzamala",
            "Hawul",
            "Jere",
            "Kaga",
            "Kala/Balge",
            "Konduga",
            "Mafa",
            "Magumeri",
            "Maiduguri",
            "Ngala",
            "Nganzai",
            "Shani"
        ]
    },
    {
        id: 9,
        state: "Cross River State",
        localGovernmentAreas: [
            "Akamkpa",
            "Akpabuyo",
            "Bakassi",
            "Calabar Municipal",
            "Calabar South",
            "Ebonyi",
            "Ikom",
            "Obanliku",
            "Obubra",
            "Odukpani",
            "Okpokwu",
            "Yakuur",
            "Yala"
        ]
    },
    {
        id: 10,
        state: "Delta State",
        localGovernmentAreas: [
            "Aniocha North",
            "Aniocha South",
            "Bomadi",
            "Burutu",
            "Delta",
            "Ethiope East",
            "Ethiope West",
            "Ika North East",
            "Ika South",
            "Isoko North",
            "Isoko South",
            "Ndokwa East",
            "Ndokwa West",
            "Okpe",
            "Oshimili North",
            "Oshimili South",
            "Patani",
            "Sapele",
            "Udu",
            "Ughelli North",
            "Ughelli South",
            "Warri North",
            "Warri South",
            "Warri South-West"
        ]
    },
    {
        id: 11,
        state: "Ebonyi State",
        localGovernmentAreas: [
            "Abakaliki",
            "Afikpo North",
            "Afikpo South",
            "Ebonyi",
            "Ishielu",
            "Ivo",
            "Ohaozara",
            "Ohaukwu",
            "Onicha"
        ]
    },
    {
        id: 12,
        state: "Edo State",
        localGovernmentAreas: [
            "Akoko Edo",
            "Esan Central",
            "Esan North East",
            "Esan South East",
            "Esan West",
            "Egor",
            "Igueben",
            "Ikpoba Okha",
            "Oredo",
            "Orhionmwon",
            "Ovia North East",
            "Ovia South West",
            "Uhunmwonde"
        ]
    },
    {
        id: 13,
        state: "Ekiti State",
        localGovernmentAreas: [
            "Ado Ekiti",
            "Ekiti East",
            "Ekiti South West",
            "Ekiti West",
            "Emure",
            "Gbonyin",
            "Ijero",
            "Ikere",
            "Ilejemeje",
            "Irepodun Ifelodun",
            "Moba",
            "Oye"
        ]
    },
    {
        id: 14,
        state: "Enugu State",
        localGovernmentAreas: [
            "Enugu East",
            "Enugu North",
            "Enugu South",
            "Ezeagu",
            "Igbo Etiti",
            "Igbo Eze North",
            "Igbo Eze South",
            "Isi Uzo",
            "Nkanu East",
            "Nkanu West",
            "Obioma Ngwa",
            "Oji River",
            "Udenu",
            "Udi",
            "Nsukka"
        ]
    },
    {
        id: 15,
        state: "Gombe State",
        localGovernmentAreas: [
            "Akko",
            "Balanga",
            "Billiri",
            "Dukku",
            "Funakaye",
            "Gombe",
            "Kaltungo",
            "Kwami",
            "Nafada",
            "Shongom",
            "Yamaltu/Deba"
        ]
    },
    {
        id: 16,
        state: "Imo State",
        localGovernmentAreas: [
            "Aboh Mbaise",
            "Ahiazu Mbaise",
            "Ikeduru",
            "Isiala Mbano",
            "Isu",
            "Mbaitoli",
            "Ngor Okpala",
            "Njaba",
            "Nkwere",
            "Oguta",
            "Ohaji/Egbema",
            "Oru East",
            "Oru West",
            "Owerri Municipal",
            "Owerri West",
            "Owerri North"
        ]
    },
    {
        id: 17,
        state: "Jigawa State",
        localGovernmentAreas: [
            "Auyo",
            "Babura",
            "Dutse",
            "Garki",
            "Gumel",
            "Hadejia",
            "Kazaure",
            "Kiyawa",
            "Malam Madori",
            "Miga",
            "Ringim",
            "Sule Tankarkar",
            "Taura",
            "Yankwashi"
        ]
    },
    {
        id: 18,
        state: "Kaduna State",
        localGovernmentAreas: [
            "Birnin Gwari",
            "Chikun",
            "Giwa",
            "Igabi",
            "Jaba",
            "Jema'a",
            "Kachia",
            "Kaduna North",
            "Kaduna South",
            "Kagarko",
            "Lere",
            "Sanga",
            "Zaria"
        ]
    },
    {
        id: 19,
        state: "Kano State",
        localGovernmentAreas: [
            "Ajingi",
            "Albasu",
            "Bagwai",
            "Bebeji",
            "Bichi",
            "Bunkure",
            "Dala",
            "Dambatta",
            "Dawakin Kudu",
            "Dawakin Tofa",
            "Doguwa",
            "Gaya",
            "Gezawa",
            "Garko",
            "Garun Mallam",
            "Gaya",
            "Kano Municipal",
            "Karaye",
            "Kiru",
            "Kumbotso",
            "Makoda",
            "Minjibir",
            "Nasarawa",
            "Rogo",
            "Shanono",
            "Sumaila",
            "Tarauni",
            "Tofa",
            "Tsanyawa",
            "Warawa",
            "Wudil"
        ]
    },
    {
        id: 20,
        state: "Kogi State",
        localGovernmentAreas: [
            "Adavi",
            "Ajaokuta",
            "Ankpa",
            "Bassa",
            "Bida",
            "Dekina",
            "Ibaji",
            "Idah",
            "Igalamela/Odolu",
            "Ijumu",
            "Kabba/Bunu",
            "Kogi",
            "Lokoja",
            "Mopa-Muro",
            "Ofu",
            "Okene",
            "Okehi",
            "Olamaboro",
            "Omala",
            "Yagba East",
            "Yagba West"
        ]
    },
    {
        id: 21,
        state: "Kwara State",
        localGovernmentAreas: [
            "Asa",
            "Baruten",
            "Edu",
            "Ekiti",
            "Ilorin East",
            "Ilorin South",
            "Ilorin West",
            "Irepodun",
            "Isin",
            "Kaiama",
            "Moro",
            "Oke Ero",
            "Offa",
            "Oyun"
        ]
    },
    {
        id: 22,
        state: "Lagos State",
        localGovernmentAreas: [
            "Agege",
            "Ajeromi-Ifelodun",
            "Alimosho",
            "Apapa",
            "Epe",
            "Eti Osa",
            "Ibeju Lekki",
            "Ifako-Ijaye",
            "Ikeja",
            "Ikorodu",
            "Kosofe",
            "Lagos Mainland",
            "Lagos Island",
            "Mushin",
            "Ojo",
            "Oshodi-Isolo",
            "Somolu",
            "Surulere"
        ]
    },
    {
        id: 23,
        state: "Nasarawa State",
        localGovernmentAreas: [
            "Akwanga",
            "Karshi",
            "Keffi",
            "Keffi",
            "Nasarawa",
            "Nasarawa Eggon",
            "Obi",
            "Toto",
            "Wamba"
        ]
    },
    {
        id: 24,
        state: "Niger State",
        localGovernmentAreas: [
            "Agwara",
            "Bida",
            "Borgu",
            "Chanchaga",
            "Edati",
            "Gbako",
            "Gurara",
            "Katcha",
            "Kontagora",
            "Lapai",
            "Lavun",
            "Mokwa",
            "Paikoro",
            "Rafi",
            "Shiroro",
            "Suleja"
        ]
    },
    {
        id: 25,
        state: "Ogun State",
        localGovernmentAreas: [
            "Abeokuta North",
            "Abeokuta South",
            "Ado-Odo/Ota",
            "Egbado North",
            "Egbado South",
            "Ifo",
            "Ijebu East",
            "Ijebu North",
            "Ijebu Ode",
            "Obafemi Owode",
            "Odogbolu",
            "Remo North",
            "Sagamu",
            "Yewa North",
            "Yewa South"
        ]
    },
    {
        id: 26,
        state: "Ondo State",
        localGovernmentAreas: [
            "Akure North",
            "Akure South",
            "Ese Odo",
            "Idanre",
            "Ifedore",
            "Ilaje",
            "Odigbo",
            "Okitipupa",
            "Ondo East",
            "Ondo West",
            "Ose",
            "Owena"
        ]
    },
    {
        id: 27,
        state: "Osun State",
        localGovernmentAreas: [
            "Aiyedaade",
            "Aiyedire",
            "Boluwaduro",
            "Boripe",
            "Ede North",
            "Ede South",
            "Egbedore",
            "Ife Central",
            "Ife East",
            "Ife North",
            "Ife South",
            "Ifelodun",
            "Ilesa East",
            "Ilesa West",
            "Isokan",
            "Obokun",
            "Odo Otin",
            "Olorunda",
            "Oriade",
            "Osogbo"
        ]
    },
    {
        id: 28,
        state: "Oyo State",
        localGovernmentAreas: [
            "Akinyele",
            "Atiba",
            "Atigbo",
            "Egbeda",
            "Ibadan North",
            "Ibadan North East",
            "Ibadan North West",
            "Ibadan South East",
            "Ibadan South West",
            "Ibarapa Central",
            "Ibarapa East",
            "Ibarapa North",
            "Ido",
            "Iseyin",
            "Itesiwaju",
            "Iwajowa",
            "Ogbomosho North",
            "Ogbomosho South",
            "Oyo East",
            "Oyo West",
            "Saki East",
            "Saki West"
        ]
    },
    {
        id: 29,
        state: "Plateau State",
        localGovernmentAreas: [
            "Bokkos",
            "Jos East",
            "Jos North",
            "Jos South",
            "Kanke",
            "Langtang North",
            "Langtang South",
            "Mangu",
            "Pankshin",
            "Quan Pan",
            "Riyom",
            "Shendam",
            "Wase"
        ]
    },
    {
        id: 30,
        state: "Rivers State",
        localGovernmentAreas: [
            "Abua/Odual",
            "Ahoada East",
            "Ahoada West",
            "Akuku Toru",
            "Andoni",
            "Asari-Toru",
            "Bonny",
            "Degema",
            "Emohua",
            "Etche",
            "Gokana",
            "Ikwerre",
            "Khana",
            "Obio/Akpor",
            "Ogba/Egbema/Ndoni",
            "Ogu/Bolo",
            "Okrika",
            "Port Harcourt",
            "Tai"
        ]
    },
    {
        id: 31,
        state: "Sokoto State",
        localGovernmentAreas: [
            "Binji",
            "Bodinga",
            "Dange Shuni",
            "Gada",
            "Goronyo",
            "Gudu",
            "Illela",
            "Kebbe",
            "Kware",
            "Rabah",
            "Sabon Birni",
            "Sokoto North",
            "Sokoto South",
            "Tambuwal",
            "Tangaza",
            "Wamako",
            "Wurno",
            "Yabo"
        ]
    },
    {
        id: 32,
        state: "Taraba State",
        localGovernmentAreas: [
            "Ardo Kola",
            "Bali",
            "Donga",
            "Gashaka",
            "Gembu",
            "Ibi",
            "Jalingo",
            "Karim Lamido",
            "K不上修身",
            "Wukari"
        ]
    },
    {
        id: 33,
        state: "Yobe State",
        localGovernmentAreas: [
            "Bade",
            "Bursari",
            "Damaturu",
            "Fika",
            "Fune",
            "Geidam",
            "Jakusko",
            "Nguru",
            "Potiskum",
            "Tarmua",
            "Yunusari",
            "Yusufari"
        ]
    },
    {
        id: 34,
        state: "Zamfara State",
        localGovernmentAreas: [
            "Anka",
            "Bakura",
            "Birnin Magaji",
            "Bukkuyum",
            "Gusau",
            "Gwadabawa",
            "Maradun",
            "Shinkafi",
            "Talata Mafara",
            "Tsafe",
            "Zurmi"
        ]
    }
];
